# Generated by Django 2.0.5 on 2018-05-07 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ivatar.ivataraccount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('add_date', models.DateTimeField(default=ivatar.ivataraccount.models.utcnow)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'confirmed email',
                'verbose_name_plural': 'confirmed emails',
            },
        ),
        migrations.CreateModel(
            name='ConfirmedOpenId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('add_date', models.DateTimeField(default=ivatar.ivataraccount.models.utcnow)),
                ('openid', models.URLField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'confirmed OpenID',
                'verbose_name_plural': 'confirmed OpenIDs',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=ivatar.ivataraccount.models.utcnow)),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('data', models.BinaryField()),
                ('format', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='UnconfirmedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('add_date', models.DateTimeField(default=ivatar.ivataraccount.models.utcnow)),
                ('email', models.EmailField(max_length=254)),
                ('verification_key', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unconfirmed_email',
                'verbose_name_plural': 'unconfirmed_emails',
            },
        ),
        migrations.CreateModel(
            name='UnconfirmedOpenId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('add_date', models.DateTimeField(default=ivatar.ivataraccount.models.utcnow)),
                ('openid', models.URLField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'unconfirmed OpenID',
                'verbose_name_plural': 'unconfirmed_OpenIDs',
            },
        ),
        migrations.AddField(
            model_name='confirmedopenid',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openids', to='ivataraccount.Photo'),
        ),
        migrations.AddField(
            model_name='confirmedopenid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmedemail',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='ivataraccount.Photo'),
        ),
        migrations.AddField(
            model_name='confirmedemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
