# Generated by Django 2.0.5 on 2018-05-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIDAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.TextField(max_length=2047)),
                ('handle', models.CharField(max_length=255)),
                ('secret', models.TextField(max_length=255)),
                ('issued', models.IntegerField()),
                ('lifetime', models.IntegerField()),
                ('assoc_type', models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OpenIDNonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.CharField(max_length=255)),
                ('timestamp', models.IntegerField()),
                ('salt', models.CharField(max_length=128)),
            ],
        ),
    ]
