# Generated by Django 2.0.5 on 2018-05-08 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0002_openidassociation_openidnonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedemail',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='confirmedemail',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='confirmedopenid',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='confirmedopenid',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='unconfirmedemail',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='unconfirmedemail',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='unconfirmedopenid',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='unconfirmedopenid',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
    ]
