# Generated by Django 2.0.6 on 2018-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0005_auto_20180522_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedemail',
            name='digest_sha256',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='confirmedemail',
            name='digest',
            field=models.CharField(max_length=32),
        ),
    ]
