# Generated by Django 2.1.3 on 2018-11-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivataraccount', '0010_auto_20180705_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='access_count',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('default', 'Default theme'), ('clime', 'climes theme'), ('falko', 'falkos theme')], default='default', max_length=10),
        ),
    ]
